# Generated by Django 2.1.2 on 2020-06-11 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sample_1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_10',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_3',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_4',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_5',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_6',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_7',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_8',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_9',
        ),
        migrations.AddField(
            model_name='item',
            name='context',
            field=models.TextField(blank=True, null=True, verbose_name='記事の内容ß'),
        ),
        migrations.AddField(
            model_name='item',
            name='hashtag',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='#hashtag'),
        ),
        migrations.AddField(
            model_name='item',
            name='post_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='投稿日付'),
        ),
        migrations.AddField(
            model_name='item',
            name='recommended',
            field=models.BooleanField(blank=True, null=True, verbose_name='おすすめフラグ'),
        ),
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.CharField(default='sample title', max_length=128, verbose_name='記事のタイトル'),
        ),
    ]
