# Generated by Django 2.1.2 on 2020-06-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200612_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='recommended',
            field=models.BooleanField(default=False, verbose_name='おすすめフラグ'),
        ),
    ]
